package projecteuler

// Problem 2
// Even Fibonacci numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const (
	answerProblem2 = 4613732
)

func problem2() int64 {
	previousTerm := int64(1)
	lastTerm := int64(0)
	sum := int64(0)

	for lastTerm <= 4000000 {
		previousTerm, lastTerm = lastTerm, (previousTerm + lastTerm)
		if isEven(lastTerm) {
			sum += lastTerm
		}
	}
	return sum
}

func isEven(number int64) bool {
	return number%2 == 0
}
